### PR TITLE
Fix incorrect JSON Pointer on $ref and add 2 new tests

### PR DESCRIPTION
**Pull request by fmvilas**
As per [JSON Pointer specification](https://tools.ietf.org/html/rfc6901), the `common.yml/#userSignUp` reference is invalid. It must start with `#/`.

It was a great mistake though so I added them as invalid tests too.

### CODE REVIEW

**Comment by fmvilas** [comment]
@postatum updated the manifest.json file. Thanks for pointing it out. I think my computer is following a different order and I'm seeing a bunch of changes when I should really see 2 or 3 lines changing.

Do you think it would make sense to get rid of the manifest.json file and make the code traverse the tests directory?

**Comment by postatum** [comment]
> Do you think it would make sense to get rid of the manifest.json file and make the code traverse the tests directory?

This lib can definitely work without the manifest file. Function `runner/js/src/utils.js / listFiles` would have to be reworked to make it work that way.

The only goal of `manifest.json` was to list files in order in which respective sections appear in the spec. This guarantees that produced HTML reports list them in the same order instead of running and listing them chaotically. If you care about this, some logic from `genmanifest.js` would also have to be ported to `utils.listFiles`.

**Comment by fmvilas** [comment]
I don't actually mind the order as long as it's always the same on every PR 😄 I was also thinking it would be cool to have these tests as a Github action that would report on every parser PR (@derberg, in case you need ideas for the Github Actions hackathon).

**Comment by postatum** [comment]
> I don't actually mind the order as long as it's always the same on every PR

We could do simple `.sort()` on files names list to make sure we get a persistent order in that chaotic order :) 
I can get rid of manifest.json logic and rework the util function if you are ok with this.

**Comment by fmvilas** [comment]
I'd be more than happy 🙂 Thanks!

**Pull request merged**
