### PR TITLE
fix: fix examples invalid cases

### PR DESCRIPTION
**Pull request by BlockLucas**
Right now those cases don't have a type definition, hence they are open (can use other properties in examples) objects by default.
This PR defines the object & property in order to have a constraint for the examples, thus making them invalid.

### CODE REVIEW

**Review by postatum — APPROVED** [review]

**Comment by fmvilas** [comment]
Yo folks. Sorry, I messed it up the other day with the examples: https://github.com/asyncapi/asyncapi/pull/444. In any case, examples need to be fixed.

**Comment by jonaslagoni** [comment]
Sorry didn't notice this PR before I merged #42, which solves this as well :sweat_smile: Closing over that.

**Comment by jonaslagoni** [comment]
Well, the changes looked the same, but as Lukasz pointed out they different files all together and not what was merged 👀

**Comment by derberg** [comment]
@postatum hey, this PR looks good and you already approved. Anything against merging it?

**Comment by derberg** [comment]
I'll merge it as it is a good fix

**Pull request merged**
