### PR TITLE
chore: add CODEOWNERS

### PR DESCRIPTION
**Pull request by derberg**
@gutee @jstoiko @AgustinBettati I got info from @fmvilas that you'd like to continue to be gatekeepers for this repository. Remember that this means we need you to be responsive here, especially when I hope next year we will start research on how TCK could be used as an NPM package.

Let me know if you need some help and more codeowners (maintainers) at start.

Please also make yourself aware of our open governance and that the fact of being a CODEOWNER enables you to become a [TSC member](https://github.com/asyncapi/community/blob/master/CHARTER.md#2-technical-steering-committee)? In case you are interested, please [open up a PR against this file](https://github.com/asyncapi/community/blob/master/TSC_MEMBERS.json)

### CODE REVIEW

**Comment by jstoiko** [comment]
@derberg Sure. Not sure what you have in mind but we can definitely provide guidance. The codeowners currently listed are focusing more on the test case part but if we need to refactor this project at some point like you seem to suggest, I will try to identify more people.

**Comment by derberg** [comment]
@jstoiko it is related to https://github.com/asyncapi/parser-js/issues/137 but we were also thinking about how we could leverage test cases in code generator testing (but this is way more complex).

Anyway ❤️ awesome you want to continue as maintainers here 🙇🏼 

@gutee @jstoiko @AgustinBettati I need you to approve this PR in order to get it merged. And also don't forget to add yourself to TSC list if you want to help on the org level in decision making. I'm happy to explain more if you have some questions.

**Review by AgustinBettati — APPROVED** [review]

**Review by gutee — APPROVED** [review]

**Comment by derberg** [comment]
@jstoiko pinging in case notification was lost :) please approve this PR if you agree. I see other approvals are in place, so once you approve, I will merge and you are welcome to submit PR against the TSC_MEMBERS list

**Comment by derberg** [comment]
@jstoiko I see you approved https://github.com/asyncapi/raml-dt-schema-parser/pull/93, please also approve this one so we can close it before Christmas :)

**Review by jstoiko — APPROVED** [review]

**Comment by derberg** [comment]
@jstoiko @gutee @AgustinBettati welcome aboard! you should get GH invites to me maintainers of this repo

> Please also make yourself aware of our open governance and that the fact of being a CODEOWNER enables you to become a TSC member? In case you are interested, please open up a PR against this file

as wrote in description, if you want to help us out manage the AsyncAPI Initiative on a organization level, not just tck, then please add yourself to TSC members list

**Pull request merged**
